<?php include 'includes/html.inc' ?>
<html>
    <head>
        <?php if (!isset($pageTitle)) $pageTitle = "xx"; ?>
        <?php include 'includes/head.inc' ?>        
        <?php include 'functions/display_date.php'?>
        <title><?php echo $pageTitle; ?></title>
        <script src="js/main.js" type="text/javascript"></script>
    </head>
    
    <body>
        <?php include 'includes/header.inc'?>
		