    </div>
    <!--END OF MAIN CONTENTS-->	
    
    <!--FOOTER CONTENTS-->
    <div id="footer">
        <!--TOPICS-->
        <div class="topics">
            <div class="col first-col">
                <a href="unavailable.php">
                    <h4>HOT TOPIC</h4>
                    <img src="http://yourmemento.naa.gov.au/wp-content/uploads/2013/07/GovHack-audience_4881.jpg"/>
                </a>
            </div>
            <div class="col">
                <a href="unavailable.php">
                    <h4>NEWS OF THE WEEK</h4>
                    <img src="http://www.queensland.aussietrueblue.com/brisbane-museum.jpg"/>
                </a>
            </div>
            <div class="col">
                <a href="unavailable.php">
                    <h4>LATEST POST</h4>
                    <img src="http://resources1.news.com.au/images/2010/03/06/1225837/701153-storm-chaos.jpg"/>
                </a>
            </div>
            <div class="col last-col">
                <a href="unavailable.php">
                    <h4>ADMIN FEED</h4>
                    <img src="images/ogre.png"/>
                </a>
            </div>
        </div>
        <!--END OF TOPICS-->
        
        
        <br/>
        <!--INFORMATION TAG-->
        <div class="info-tag">
            <div class="disclaimer">
                <a href="unavailable.php">Contact Us</a
                ><a href="unavailable.php">Copyright </a
                ><a href="unavailable.php">Terms and Conditions </a>
            </div>
            Designed by QueenslandBrainMaps - QUT
            
        </div>
        <!--END OF INFORMATION TAG-->
        
    </div>
    <!--END OF FOOTER CONTENTS-->
    
    
</div>    
<!--END OF CONTENT WRAPPER-->