<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">
<link href="css/main.css" rel="stylesheet" type="text/css"/>
<link href="css/font.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="includes/font-awesome/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<script src="js/main.js"></script>
<script>
	$(document).ready(function(e){
		$('#brisbane-city-slide').on('click',function(){
			$('#brisbane-city-child').slideToggle();
		});
	})
	$(document).ready(function(e){
		$('#education-slide').on('click',function(){
			$('#education-child').slideToggle();
		});
	})
	$(document).ready(function(e){
		$('#n-p-sciences-slide').on('click',function(){
			$('#n-p-sciences-child').slideToggle();
		});
	})
	$(document).ready(function(e){
		$('#engineering-slide').on('click',function(){
			$('#engineering-child').slideToggle();
		});
	})
	$(document).ready(function(e){
		$('#buildings-slide').on('click',function(){
			$('#buildings-child').slideToggle();
		});
	})
	$(document).ready(function(e){
		$('#tourism-slide').on('click',function(){
			$('#tourism-child').slideToggle();
		});
	})
</script>