<!--LEFT BAR CONTENTS-->
<div class="leftBar">
	<ul>
		<li>
		<div class="nav">
			<div class="parent-wrapper">
                <div class="parent" id="brisbane-city">
                    <div class="icon"><i class="fa fa-book"></i></div>
                    <div class="title">Brisbane City</div>
                    <div class="slide" id="brisbane-city-slide"><i class="fa fa-caret-square-o-down"></i></div>
                </div>
				<div class="child-wrapper" id="brisbane-city-child">
					<a>
                    <div class="child" onclick="navToggleChild('BrisbaneCity', 'BikeRacks')">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Bike Racks</div>
					</div>
					</a>
					<a>
                    <div class="child" onclick="navToggleChild('BrisbaneCity', 'DrinkingFountains')">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Drinking Fountains</div>
					</div>
					</a>
					<a>
                    <div class="child" onclick="navToggleChild('BrisbaneCity', 'WiFi')">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Free WiFI</div>
					</div>
					</a>
					<a>
                    <div class="child" onclick="navToggleChild('BrisbaneCity', 'GolfCourse')">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Golf Courses</div>
					</div>
					</a>
					<a>
                    <div class="child" onclick="navToggleChild('BrisbaneCity', 'ParkFacility')">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Parks</div>
					</div>
					</a>
					<a>
                    <div class="child" onclick="navToggleChild('BrisbaneCity', 'Pool')">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Public Pools</div>
					</div>
					</a>
				</div>
			</div>
		</div>
		</li>
		<li>
		<div class="nav">
            <div class="parent-wrapper">
                <div class="parent" id="education-parent">
                    <div class="icon"><i class="fa fa-book"></i></div>
                    <div class="title">Education</div>
                    <div class="slide" id="education-slide"><i class="fa fa-caret-square-o-down"></i></div>
                </div>
                <div class="child-wrapper" id="education-child">
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">University</div>
                    </div>
					</a>
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">TAFE</div>
                    </div>
					</a>
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">High School</div>
                    </div>
					</a>
					<a>					
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Primary School</div>
                    </div>
					</a>
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Kindergarten</div>
                    </div>
					</a>
                </div>
            </div>
        </div>		
		</li>
        <li>
		<div class="nav">
			<div class="parent-wrapper">
                <div class="parent" id="engineering">
                    <div class="icon"><i class="fa fa-book"></i></div>
                    <div class="title">Engineering</div>
                    <div class="slide" id="engineering-slide"><i class="fa fa-caret-square-o-down"></i></div>
                </div>
				<div class="child-wrapper" id="engineering-child">
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Nothing</div>
					</div>
					</a>
				</div>
			</div>
		</div>
		</li>
        <li>
		<div class="nav">
			<div class="parent-wrapper">
                <div class="parent" id="n-p-sciences">
                    <div class="icon"><i class="fa fa-book"></i></div>
                    <div class="title">Sciences</div>
                    <div class="slide" id="n-p-sciences-slide"><i class="fa fa-caret-square-o-down"></i></div>
                </div>
				<div class="child-wrapper" id="n-p-sciences-child">
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Nothing</div>
					</div>
					</a>
				</div>
			</div>
		</div>
		</li>
		<li>
		<div class="nav">
			<div class="parent-wrapper">
                <div class="parent" id="buildings">
                    <div class="icon"><i class="fa fa-book"></i></div>
                    <div class="title">Buildings</div>
                    <div class="slide" id="buildings-slide"><i class="fa fa-caret-square-o-down"></i></div>
                </div>
				<div class="child-wrapper" id="buildings-child">
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Nothing</div>
					</div>
					</a>
				</div>
			</div>
		</div>
		</li>
		<li>
		<div class="nav">
			<div class="parent-wrapper">
                <div class="parent" id="tourism">
                    <div class="icon"><i class="fa fa-book"></i></div>
                    <div class="title">Tourism</div>
                    <div class="slide" id="tourism-slide"><i class="fa fa-caret-square-o-down"></i></div>
                </div>
				<div class="child-wrapper" id="tourism-child">
					<a>
                    <div class="child">
                        <div class="spacer">&nbsp;</div>
                        <div class="title">Nothing</div>
					</div>
					</a>
				</div>
			</div>
		</div>
		</li>
	</ul>
</div>
<!--END OF LEFT BAR CONTENTS-->